version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000